In [39]:
import pandas as pd

In [40]:
def canon_or_notcanon(sequence):
     alphabet = set("ACDEFGHIKLMNPQRSTVWY")
     sequence = sequence.strip()
     is_canon = True
     for res in set(sequence):
         if res not in alphabet:
             is_canon = False
     return is_canon

In [41]:
canon= []
notcanon= []

In [42]:
antiviral=pd.read_csv("Antiviral/antiviral_nomod_canon.csv")
hlp=pd.read_csv("HLP/HLP.csv")
peplife=pd.read_csv("PEPLIFE/PEP_LIFE_nomod_canon.csv")
peptherdia=pd.read_csv("PepTherDia/PepTherDia_nomod_canon.csv")
plifepred=pd.read_csv("Plifepred/plifepred_nomod_canon.csv")
serum=pd.read_csv("Serum/serum_nomod_canon.csv")

In [43]:
df_concat=pd.concat([antiviral,hlp,peplife,peptherdia,plifepred,serum])

/tmp/ipykernel_42750/2429325579.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_concat=pd.concat([antiviral,hlp,peplife,peptherdia,plifepred,serum])

In [44]:
#df_concat['is_mod'].value_counts()

In [45]:
#dimensiones de datos duplicados
df_concat[df_concat.duplicated(subset=['sequence'], keep=False)].shape

(2016, 5)

In [46]:
#dimensiones de datos no duplicados
df_concat[~df_concat.duplicated(subset=['sequence', 'modifications'], keep=False)].shape

KeyError: Index(['modifications'], dtype='object')

In [ ]:
#separacion de datos duplicados que tengan la misma secuencia y modificaciones (se examinan las secuencia, si modificaiones y secuencia es igual pero half_life_seconds es diferente se borran todos los duplicados)
df_data_duplicated=(df_concat[df_concat.duplicated(subset=['sequence', 'modifications'], keep=False)]).sort_values(by='sequence')
df_data_duplicated

,sequence,half_life_seconds,is_mod,modifications,experimental_characteristics
224,ACDTATCVTHRLAGLLSRSGGVVKNNFVPTNVGSKAF,258.0,False,NaN,NaN
750,ACDTATCVTHRLAGLLSRSGGVVKNNFVPTNVGSKAF,414.0,False,NaN,Intravenous injection into human
769,ADSGEGDFLAEGGGVR,30.0,False,NaN,Intravenous injection in lateral vein of norma...
153,ADSGEGDFLAEGGGVR,5400.0,False,NaN,NaN
212,AGGDASGE,453.0,False,NaN,NaN
...,...,...,...,...,...
189,YPIKPEAPGEDASPEELNRYYASLRHYLNLVTRQRY,216.0,False,NaN,NaN
864,YRGDS,30.0,False,NaN,Intravenously injected to C57BL6 mice
170,YRGDS,30.0,False,NaN,NaN
553,YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF,31680.0,False,NaN,Male cynomolgus monkey blood plasma Intravenous
52,YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF,31680.0,False,NaN,NaN

In [ ]:
#separacion de datos duplicados que tengan la misma secuencia, modificaciones y half_life_seconds (de esto solo se guarda una copia) 
df_data_duplicated_2=(df_concat[df_concat.duplicated(subset=['sequence', 'modifications', 'half_life_seconds'], keep=False)]).sort_values(by='sequence')
df_data_duplicated_2

,sequence,half_life_seconds,is_mod,modifications,experimental_characteristics
1027,AGGDASGE,453.0,False,NaN,Mongrel dog plasmaDose i/v injected
212,AGGDASGE,453.0,False,NaN,NaN
217,APGPR,300.0,False,NaN,NaN
1032,APGPR,300.0,False,NaN,Human Serum
18,DAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVV,144.0,False,NaN,Intravenouly injected into male B6SJLF1/J mice...
...,...,...,...,...,...
47,YIGSR,60.0,False,NaN,NaN
170,YRGDS,30.0,False,NaN,NaN
864,YRGDS,30.0,False,NaN,Intravenously injected to C57BL6 mice
52,YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF,31680.0,False,NaN,NaN
553,YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF,31680.0,False,NaN,Male cynomolgus monkey blood plasma Intravenous

In [ ]:
#separacion de datos no duplicados
df_not_duplicated=(df_concat[~df_concat.duplicated(subset=['sequence', 'modifications'], keep=False)]).sort_values(by='sequence')
#se concatenan los datos no duplicados con los datos duplicados pero que se mantiene una copia
df_not_duplicated=pd.concat([df_not_duplicated, df_data_duplicated_2])
df_not_duplicated

,sequence,half_life_seconds,is_mod,modifications,experimental_characteristics
575,((POG)5 (PQGPGGPPG) (POG)5)3,580.0,True,"C-Terminal Amidation, N-Terminal",Not reported
576,((POG)5 (PQGPGSPPG) (POG)5)3,910.0,True,"C-Terminal Amidation, N-Terminal",Not reported
577,((POG)5 (PVGAAGATG) (POG)5)3,345.0,True,"C-Terminal Amidation, N-Terminal",Not reported
578,((POG)5 (PVGAASATG) (POG)5)3,655.0,True,"C-Terminal Amidation, N-Terminal",Not reported
1052,(CBC)KFAP,1464.0,True,"N-Terminal, Chemical Modification: Proline Rin...",Dose i/v injected Rat blood
...,...,...,...,...,...
47,YIGSR,60.0,False,NaN,NaN
170,YRGDS,30.0,False,NaN,NaN
864,YRGDS,30.0,False,NaN,Intravenously injected to C57BL6 mice
52,YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF,31680.0,False,NaN,NaN
553,YTSLIHSLIEESQNQQEKNEQELLELDKWASLWNWF,31680.0,False,NaN,Male cynomolgus monkey blood plasma Intravenous

In [ ]:
#se borran valores nulos y se eliminan los duplicados sobrantes de los que se guarda una copia y se ordenan los datos
df_not_duplicated.dropna(subset=['sequence', 'half_life_seconds'], inplace=True)
df_not_duplicated.drop_duplicates(subset=['sequence', 'modifications'], keep='first', inplace=True)
df_not_duplicated.sort_index(inplace=True)

In [ ]:
df_not_duplicated

,sequence,half_life_seconds,is_mod,modifications,experimental_characteristics
0,GSIGAASMEFCFDVFK,0.0097,NaN,NaN,HLP
0,GSIGAASMEF,2.7013,NaN,NaN,HLP
0,AC-GFGCNGPWNEDDLRCHNHCKSIKGYKGGYCAKGGFVCKCY-NH2,3600.0000,False,NaN,rat
0,RRWQWR,1800.0000,False,NaN,Human serum
0,XXGDWPC-NH2,9000.0000,True,"deamino, NH2",NaN
...,...,...,...,...,...
1105,FNAPFDVGIKLSGAQYQQHGRAL,1320.0000,True,C-Terminal Amidation,Intravenous injection of peptide into Sprague...
1106,FNAPFDVGIKLSGVQYQQHSQAL,3906.0000,True,C-Terminal Amidation,Mouse plasma
1107,FNAPFDVGIKLSGVQYQQHSQAL,906.0000,True,"C-Terminal Amidation, Chemical Modification: I...",Mouse liver homogenate
1108,ASISGRDTHRLTRTLNCSSIVKEIIGKLPEPELKTDDEGPSLRNKS...,126.0000,True,"Cyclic, Chemical Modification: Glycosylation A...",Injected intravenously in Balb/c mice blood
1109,HPAGKRPCKMQAFRIWDTNQKTFYLRNNQLIAGYLQGPNTKLEEKI...,630.0000,True,"Cyclic, Chemical Modification: Glycosylation A...",Rat blood

In [ ]:
df_not_duplicated.to_csv('all_data.csv', index=False)

In [ ]:
all_data_mod=df_not_duplicated[df_not_duplicated['is_mod']==True]
all_data_nomod=df_not_duplicated[df_not_duplicated['is_mod']==False]

In [ ]:
all_data_mod.to_csv('all_data_mod.csv',index=False)
all_data_nomod.to_csv('all_data_nomod.csv',index=False)

In [ ]:
for sequence in all_data_nomod["sequence"].unique():
    if canon_or_notcanon(sequence):
        canon.append(sequence)
    else:
        notcanon.append(sequence)

In [ ]:
all_data_canon = all_data_nomod[all_data_nomod["sequence"].isin(canon)]
all_data_notcanon = all_data_nomod[all_data_nomod["sequence"].isin(notcanon)]

In [ ]:
all_data_canon.to_csv('all_data_nomod_canon.csv',index=False, columns=["sequence","half_life_seconds", "experimental_characteristics"])
all_data_notcanon.to_csv('all_data_nomod_notcanon.csv',index=False, columns=["sequence","half_life_seconds", "experimental_characteristics"])